# Section 3: Learning numpy

References: 
1. http://cs231n.github.io/python-numpy-tutorial/
2. http://docs.scipy.org/doc/numpy/reference/

##### Overview

+ Installation: pip install numpy
+ Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## Lecture 7: Arrays


In [10]:
import numpy as np

## create array from list

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

print(my_array1)

my_list2 = [21,22,23,24]

my_lists = [my_list1, my_list2]

print(my_lists)

[1 2 3 4]
[[1, 2, 3, 4], [21, 22, 23, 24]]


In [12]:
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])

In [13]:
my_array2.shape ## 2-dimensional array is a matrix. Dimensions obtainable by shape()

(2, 4)

In [15]:
my_array2.dtype ## data type in array

dtype('int64')

In [16]:
np.zeros(5) ## floating 0s

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
my_zero_array = np.zeros(5)

my_zero_array.dtype

dtype('float64')

In [19]:
np.ones([5,5]) ## multi-dimensional array of 1s

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
np.eye(5) ## identity matrix, identity array

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,50,2) ## from, to, step

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])