# Section 3: Learning numpy

References: 
1. http://cs231n.github.io/python-numpy-tutorial/
2. http://docs.scipy.org/doc/numpy/reference/

##### Overview

+ Installation: pip install numpy
+ Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## Lecture 7: Arrays intro


In [2]:
import numpy as np

## create array from list

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

print(my_array1)

my_list2 = [21,22,23,24]

my_lists = [my_list1, my_list2]

print(my_lists)

[1 2 3 4]
[[1, 2, 3, 4], [21, 22, 23, 24]]


In [12]:
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])

In [13]:
my_array2.shape ## 2-dimensional array is a matrix. Dimensions obtainable by shape()

(2, 4)

In [15]:
my_array2.dtype ## data type in array

dtype('int64')

In [16]:
np.zeros(5) ## floating 0s

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
my_zero_array = np.zeros(5)

my_zero_array.dtype

dtype('float64')

In [3]:
np.ones([5,5]) ## multi-dimensional array of 1s

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
np.eye(5) ## identity matrix, identity array

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.arange(5,50,2) ## from, to, step

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

## Lecture 8: Using Arrays and Scalars

In [9]:
import numpy as np

5/2 ## python 3, treats as floating. python 2, treats as integer

from __future__ import division ## to explicitly import from Python 3 (if using Python 2) or other future versions

5/2

2.5

In [12]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [15]:
### Array operations

## multiplication

arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [16]:
## subtraction

arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
## inverse

1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [19]:
## raised to power

arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

## Lecture 9: Indexing Arrays

In [1]:
import numpy as np

In [22]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[8] ## index

8

In [24]:
## range

arr[1:5]

array([1, 2, 3, 4])

In [25]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [26]:
arr[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[3:-3]

array([3, 4, 5, 6, 7])

In [29]:
## setting values in a range

arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [30]:
## reset

arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
## Slicing an array

slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [32]:
slice_of_arr[:] = 99 ## select ALL elements

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [34]:
## NOTE: changing the slice changed original array as well. 
## This is because slice only creates a VIEW of the original data

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
## Explicitly create a copy variable to separate operations

arr_copy = arr.copy() ## copy() is a method in Array instance variable

arr_copy

slice_arr_copy = arr_copy[1:-2]

slice_arr_copy

array([99, 99, 99, 99, 99,  6,  7,  8])

In [11]:
## Indexing 2-d array

arr_2d = np.array([[1,2,3,4,5],[5,10,15,20,25],[500,550,600,650,700]])

arr_2d

[[  1   2   3   4   5]
 [  5  10  15  20  25]
 [500 550 600 650 700]]


array([500, 550, 600, 650, 700])

In [13]:
## Row-wise indexing
arr_2d[0] ## equal to arr_2d[0,]

array([1, 2, 3, 4, 5])

In [14]:
arr_2d[1]

array([ 5, 10, 15, 20, 25])

In [15]:
arr_2d[2]

array([500, 550, 600, 650, 700])

In [19]:
arr_2d[1,2] ## Specific element from a row, column combo

15

In [20]:
arr_2d[1][2] ## x,y and [x][y] are both equivalent indexes for numpy Arrays

15

In [21]:
## 2-d slicing

arr_2d[:2,1:]

array([[ 2,  3,  4,  5],
       [10, 15, 20, 25]])

In [23]:
## Fancy indexing

arr2d = np.zeros((10,10))

arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [25]:
arr_length = arr2d.shape[1]

arr_length

10

In [29]:
for i in range(arr_length):
    arr2d[i] = 1

arr2d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [31]:
for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [32]:
## Fancy indexing allows to index based on values in an array

arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [33]:
arr2d[[5,9,1]] ## order of values not important

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## Lecture 10: Array Transposition